include:
  - path: devToolsTarget.yml
    relativePaths: true
name: ItunesInfo
options:
  usesTabs: false
  bundleIdPrefix: com.aleksey.ermolaev.ItunesInfo
  xcodeVersion: '12.1'
  deploymentTarget: 13.0
  groupSortPosition: top
  generateEmptyDirectories: true
  minimumXcodeGenVersion: '2.18.0'
  createIntermediateGroups: true
  transitivelyLinkDependencies: true
  directlyEmbedCarthageDependencies: false

packages:
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    from: 2.7.1

configFiles:
  Debug: Sources/ItunesInfo/Configs/Debug.xcconfig
  Release: Sources/ItunesInfo/Configs/Release.xcconfig

targets:
  ItunesInfo:
    info:
      path: Sources/ItunesInfo/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
        CFBundleDisplayName: ItunesInfo
        ROOT_URL: $(ROOT_URL)
    sources: 
      - path: Sources/ItunesInfo
    type: application
    platform: iOS
    deploymentTarget: 13.0
    configFiles:
      Debug: Sources/ItunesInfo/Configs/Debug.xcconfig
      Release: Sources/ItunesInfo/Configs/Release.xcconfig
    settings:
      base:
        INFOPLIST_FILE: Sources/ItunesInfo/Info.plist
        MARKETING_VERSION: 1.0
    postCompileScripts:
      - script: |
              if which swiftlint >/dev/null; then
                  swiftlint
              else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
              fi
      - name: Run SwiftLint
    dependencies: 
      - package: Swinject
      - target: DevTools
      - framework: Carthage/Build/Kingfisher.xcframework
      - framework: Carthage/Build/SnapKit.xcframework

    fileGroups:
      - Sources/Fora Soft Evaluation Tests (iOS) v2.2.pdf
  

schemes:
  ItunesInfo:
    build:
      targets:
        ItunesInfo: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

